version: '3.5'

services:
  id-service:
    image: chusj/overture-id:0.2.0
    deploy:
      mode: replicated
      replicas: 1
    environment:
      SERVICE_PORT: 8787
      IDS_SOURCE: clin_elasticsearch
      ELASTISEARCH_URL: http://elastic:9200
    networks:
      - overture
      - proxy

networks:
  overture:
    external: true
  proxy:
    external: true