version: '3.5'

services:
  id-service:
    image: chusj/overture-id:dev
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8787:8787"
    environment:
      SERVICE_PORT: 8787
      SOURCE_LOGGER: console_debug
      IDS_SOURCE: clin_elasticsearch
      ELASTISEARCH_URL: http://elastic:9200
    volumes:
      - ./overture-id-service/src:/opt/app
    networks:
      - overture
      - proxy
  song-metadata-resolver:
    image: chusj/song-metadata-resolver:dev
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "9191:9191"
    environment:
      SERVICE_PORT: 8787
      SOURCE_LOGGER: console_debug
      ELASTISEARCH_URL: http://elastic:9200
    volumes:
      - ./song-metadata-resolver/src:/opt/app
    networks:
      - overture
      - proxy


networks:
  overture:
    external: true
  proxy:
    external: true